server:
  port: 8080

spring:
  cloud:
    config:
      fail-fast: true
      retry:
        useRandomPolicy: true
        max-interval: 6000
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: shopping_cart_service_route
          uri: lb://shopping-cart
          predicates:
            - Path=/shopping-cart/**
          filters:
            - PrefixPath=/api/v1
        - id: shopping_store_service_route
          uri: lb://shopping-store
          predicates:
            - Path=/shopping-store/**
          filters:
            - PrefixPath=/api/v1
            - name: Retry
              args:
                retries: 3
                statuses:
                  - INTERNAL_SERVER_ERROR
                  - SERVICE_UNAVAILABLE
                methods:
                  - GET
                backoff:
                  firstBackoff: 500ms
                  maxBackoff: 2000ms
                  factor: 2
                  basedOnPreviousValue: true

logging:
  level:
    ru.yandex.practicum.gateway: DEBUG