spring:
  application:
    name: collector

server:
  port: 8080

grpc:
  server:
    port: 59091

logging:
  level:
    ru.yandex.practicum.collector: DEBUG
    org.springframework.web: DEBUG
    org.apache.kafka: INFO

kafka:
  producer:
    bootstrap-servers: localhost:9092
    key-serializer: org.apache.kafka.common.serialization.StringSerializer
    value-serializer: ru.yandex.practicum.collector.service.AvroSerializer
    acks: all
    retries: 3
    enable-idempotence: true
    batch-size: 16384
    linger-ms: 10
    buffer-memory: 33554432
    request-timeout-ms: 30000
    delivery-timeout-ms: 120000
  topics:
    sensors: telemetry.sensors.v1
    hubs: telemetry.hubs.v1