spring:
  application:
    name: collector
  config:
    import: configserver:http://localhost:8888
  cloud:
    config:
      fail-fast: true
      retry:
        useRandomPolicy: true
        max-interval: 6000

server:
  port: 8080

grpc:
  server:
    port: 59091

logging:
  level:
    ru.yandex.practicum.collector: DEBUG
    org.springframework.web: DEBUG
    org.apache.kafka: INFO