analyzer:
  kafka:
    bootstrap-servers: localhost:9092
    snapshot-consumer:
      group-id: analyzer-snapshot-group
      auto-offset-reset: earliest
      enable-auto-commit: false
      poll-timeout-ms: 1000
      commit-batch-size: 100
    hub-event-consumer:
      group-id: analyzer-hub-group
      auto-offset-reset: earliest
      enable-auto-commit: false
      poll-timeout-ms: 1000
      commit-batch-size: 100
    topics:
      snapshots: telemetry.snapshots.v1
      hub-events: telemetry.hubs.v1